// exporters.ts — turn the semantic model into formal / typeset artifacts.
// Lean 4 and JSON go in dependency (topological) order; LaTeX follows document
// order. These are faithful skeletons: proofs are left as `sorry` / stubs.

import { SemanticNode, Graph, NodeKind, KIND_LABEL } from './types';

function ordered(nodes: SemanticNode[], graph: Graph): SemanticNode[] {
  if (!graph.order.length) return nodes;
  return graph.order.map((id) => graph.byId[id]).filter(Boolean);
}

function ident(label: string): string {
  const s = label.replace(/[^A-Za-z0-9_]/g, '_').replace(/^(\d)/, '_$1');
  return s || 'anon';
}

const LEAN_KEYWORD: Partial<Record<NodeKind, string>> = {
  theorem: 'theorem', lemma: 'theorem', proposition: 'theorem', corollary: 'theorem', axiom: 'axiom',
};

export function exportLean(nodes: SemanticNode[], graph: Graph): string {
  const seq = ordered(nodes, graph);
  const out: string[] = [
    '/-', '  Generated by the Semantic Logic Editor.',
    '  A skeleton: statements are stubbed with `sorry`; fill them in.', '-/', '',
    'namespace Document', '',
  ];
  seq.forEach((n) => {
    if (n.kind === 'proof' || n.kind === 'remark' || n.kind === 'example') return;
    const doc = n.body ? n.body.split('\n').map((l) => '-- ' + l).join('\n') + '\n' : '';
    const uses = n.deps.length ? `-- uses: ${n.deps.join(', ')}\n` : '';
    const id = ident(n.label);
    if (n.kind === 'definition' || n.kind === 'notation') {
      out.push(`${doc}${uses}def ${id} : Prop := sorry`, '');
    } else if (n.kind === 'axiom') {
      out.push(`${doc}${uses}axiom ${id} : Prop`, '');
    } else {
      out.push(`${doc}${uses}theorem ${id} : True := by`, '  sorry', '');
    }
  });
  out.push('end Document', '');
  return out.join('\n');
}

const LATEX_ENV: Partial<Record<NodeKind, string>> = {
  definition: 'definition', theorem: 'theorem', lemma: 'lemma', proposition: 'proposition',
  corollary: 'corollary', axiom: 'axiom', example: 'example', remark: 'remark',
};

export function exportLatex(nodes: SemanticNode[]): string {
  const head = [
    '\\documentclass{article}',
    '\\usepackage{amsmath,amssymb,amsthm}',
    '\\newtheorem{theorem}{Theorem}[section]',
    '\\newtheorem{lemma}[theorem]{Lemma}',
    '\\newtheorem{proposition}[theorem]{Proposition}',
    '\\newtheorem{corollary}[theorem]{Corollary}',
    '\\newtheorem{axiom}{Axiom}',
    '\\theoremstyle{definition}',
    '\\newtheorem{definition}{Definition}[section]',
    '\\newtheorem{example}{Example}[section]',
    '\\theoremstyle{remark}',
    '\\newtheorem*{remark}{Remark}',
    '\\begin{document}', '',
  ];
  const body: string[] = [];
  nodes.forEach((n) => {
    const esc = (s: string) => s.replace(/([&%#_])/g, '\\$1');
    if (n.kind === 'proof') {
      body.push(`\\begin{proof}[Proof of \\ref{${ident(n.proves || '')}}]`, esc(n.body), '\\end{proof}', '');
      return;
    }
    if (n.kind === 'notation') { body.push('% Notation: ' + esc(n.body), ''); return; }
    const env = LATEX_ENV[n.kind] || 'remark';
    body.push(`\\begin{${env}}[${esc(n.label)}]\\label{${ident(n.label)}}`, esc(n.body), `\\end{${env}}`, '');
  });
  return head.concat(body, ['\\end{document}', '']).join('\n');
}

export function exportJSON(nodes: SemanticNode[], graph: Graph): string {
  return JSON.stringify({
    nodes: nodes.map((n) => ({ id: n.id, label: n.label, kind: n.kind, body: n.body, proves: n.proves, deps: n.deps, line: n.line })),
    edges: graph.edges,
    topologicalOrder: graph.order.map((id) => graph.byId[id]?.label || id),
    acyclic: graph.acyclic,
    cycles: graph.cycles.map((c) => c.map((id) => graph.byId[id]?.label || id)),
  }, null, 2);
}

export function exportMarkdown(nodes: SemanticNode[], graph: Graph): string {
  const out: string[] = ['# Document', ''];
  nodes.forEach((n) => {
    out.push(`### ${KIND_LABEL[n.kind]} — ${n.label}`);
    if (n.deps.length) out.push(`*depends on: ${n.deps.join(', ')}*`);
    if (n.body) out.push('', n.body);
    out.push('');
  });
  if (graph.order.length) out.push('---', '', '**Topological order:** ' + graph.order.map((id) => graph.byId[id]?.label || id).join(' → '));
  return out.join('\n');
}


const TPTP_ROLE: Partial<Record<NodeKind, string>> = {
  definition: 'axiom', notation: 'axiom', axiom: 'axiom',
  theorem: 'conjecture', lemma: 'conjecture', proposition: 'conjecture', corollary: 'conjecture',
};

// TPTP FOF skeleton (first-order form). Bodies are prose, so formulas are stubbed
// as $true and carried as comments — a scaffold for an automated theorem prover.
export function exportTPTP(nodes: SemanticNode[], graph: Graph): string {
  const seq = ordered(nodes, graph);
  const out: string[] = ['% Generated by the Semantic Logic Editor — TPTP FOF skeleton.', '% Replace $true with the real first-order formula for each statement.', ''];
  seq.forEach((n) => {
    const role = TPTP_ROLE[n.kind];
    if (!role) return;
    const name = ident(n.label).toLowerCase();
    if (n.body) out.push('% ' + n.body.replace(/\n/g, ' '));
    if (n.deps.length) out.push('% uses: ' + n.deps.join(', '));
    out.push(`fof(${name}, ${role}, ( $true )).`, '');
  });
  return out.join('\n');
}

// Graphviz DOT of the dependency graph — render with `dot -Tsvg`.
const DOT_COLOR: Record<string, string> = {
  definition: '#4a37c8', notation: '#4a37c8', theorem: '#0c7d8f', lemma: '#0c7d8f',
  proposition: '#0c7d8f', corollary: '#0c7d8f', axiom: '#b87908', proof: '#147a4f',
  example: '#8a6d3b', remark: '#6b6d67',
};
export function exportDOT(nodes: SemanticNode[], graph: Graph): string {
  const out: string[] = ['digraph Document {', '  rankdir=RL;', '  node [shape=box, style="rounded,filled", fontname="monospace", fillcolor="#ffffff"];'];
  nodes.forEach((n) => {
    const label = (n.label || n.kind).replace(/"/g, '\\"');
    out.push(`  "${n.id}" [label="${label}", color="${DOT_COLOR[n.kind] || '#666'}"];`);
  });
  graph.edges.forEach((e) => out.push(`  "${e.from}" -> "${e.to}";`));
  out.push('}', '');
  return out.join('\n');
}

export const EXPORTERS = {
  lean: { label: 'Lean 4', lang: 'lean', run: (n: SemanticNode[], g: Graph) => exportLean(n, g) },
  latex: { label: 'LaTeX', lang: 'tex', run: (n: SemanticNode[], _g: Graph) => exportLatex(n) },
  json: { label: 'JSON', lang: 'json', run: (n: SemanticNode[], g: Graph) => exportJSON(n, g) },
  markdown: { label: 'Markdown', lang: 'md', run: (n: SemanticNode[], g: Graph) => exportMarkdown(n, g) },
  tptp: { label: 'TPTP', lang: 'p', run: (n: SemanticNode[], g: Graph) => exportTPTP(n, g) },
  dot: { label: 'Graphviz', lang: 'dot', run: (n: SemanticNode[], g: Graph) => exportDOT(n, g) },
};
export type ExportKey = keyof typeof EXPORTERS;
